synapse:
  synid_file_grs: syn24184523
  synid_table_prissmm: syn22684834
  synid_folder_rcc_exports: syn24609065
  synid_folder_rca_exports: syn23286928
upload:
  BrCa:
    DFCI:
      data1: syn26160187
      header1: syn25981842
      data2: syn26160184
      header2: syn25981841
    MSK:
      data1: syn24202045
    VICC:
      data1: syn24201984
  CRC:
    DFCI:
      data1: syn25961098
      header1: syn25961099
    MSK:
      data1: syn25953196
    VICC:
      data1: syn25961124
  NSCLC:
    DFCI:
      data1: syn25582436
      header1: syn25582427
    MSK:
      data1: syn25557012
    UHN:
      data1: syn25686838
    VICC:
      data1: syn25579921
  PANC:
    DFCI:
      data1: syn25544638
      header1: syn25544639
    MSK:
      data1: syn25541828
    UHN:
      data1: syn26033209
    VICC:
      data1: syn25541702
  Prostate:
    DFCI:
      data1: syn25592216
      header1: syn25592217
    MSK:
      data1: syn25591851
    UHN:
      data1: syn25586093
    VICC:
      data1: syn25592242
output:
  BrCa: 
    rcc_id: syn24609066
    rcc_skip: 35
    rca_id: syn23286608
  CRC: 
    rcc_id: syn25578083
    rcc_skip: NA
    rca_id: syn23285418
  NSCLC: 
    rcc_id: syn25570730
    rcc_skip: NA
    rca_id: syn23285494
  PANC: 
    rcc_id: syn25578183
    rcc_skip: NA
    rca_id: syn24175803
  Prostate: 
    rcc_id: syn25610356
    rcc_skip: 36
    rca_id: syn25610393
column_name:
  variable_name: "Variable / Field Name"
  form_name: "Form Name"
  field_type: "Field Type"
  variable_mapping: "Choices, Calculations, OR Slider Labels"
  variable_type: "Text Validation Type OR Show Slider Number"
  variable_min: "Text Validation Min"
  variable_max: "Text Validation Max"
  rs_label: "Response Set Label"
  rs_value: "Response Set Values"
mapping:
  complete:
    0: "Not Started"
    1: "Data Entry Started"
    2: "Completed"
    5: "Monitoring Complete"
    6: "Form Removed"
    7: "Form Locked"
    8: "Form Signed"
  yesno_rcc: 
    0: "FALSE"
    1: "true"
  yesno_rca:
    0: "No"
    1: "Yes"
  instrument:
    ca_directed_drugs: "Ca Directed Drugs"
    cancer_diagnosis: "Cancer Diagnosis"
    cancer_panel_test: "Cancer Panel Test"
    prissmm_imaging: "Prissmm Imaging"
    prissmm_med_onc_assessment: "Prissmm Med Onc Assessment"
    prissmm_pathology: "Prissmm Pathology"
    prissmm_tumor_marker: "Prissmm Tumor Marker"
    ca_directed_radtx: "Ca Directed Radtx"
misc:
  debug: TRUE
format:
  rcc: "rcc"
  rca: "rca"
